name: 8 - Container
on: push

jobs:
  # node-docker:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:13.5.0-alpine3.10
  #   steps:
  #     - name: Log node version
  #       run: |
  #         node -v
  #         cat /etc/os-release
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node version # without container
        run: node -v
      - name: step with docker container
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: Log node version # uses container with node 12.14
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/usr/local/bin/node'
          args: '-v'
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: derekchia/simple-docker-nodejs-api # alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\",\"address\": \"dwdwd\"}' "
      - name: Get users
        run: curl http://localhost:3001/api/users
